//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.07.10 at 12:45:26 PM CEST
//
// TOSCA version: TOSCA-v1.0-cs02.xsd
//

package eu.seaclouds.tosca.model;

import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for tAppliesTo complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tAppliesTo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NodeTypeReference" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="typeRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAppliesTo", propOrder = {"nodeTypeReference"})
public class TAppliesTo {
	
	@XmlElement(name = "NodeTypeReference", required = true)
	protected List<NodeTypeReference> nodeTypeReference;


	/**
	 * Gets the value of the nodeTypeReference property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the nodeTypeReference property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getNodeTypeReference().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link TAppliesTo.NodeTypeReference }
	 *
	 *
	 */
	public List<NodeTypeReference> getNodeTypeReference() {
		if (this.nodeTypeReference == null) {
			this.nodeTypeReference = new ArrayList<NodeTypeReference>();
		}
		return this.nodeTypeReference;
	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="typeRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class NodeTypeReference {

		@XmlAttribute(name = "typeRef", required = true)
		protected QName typeRef;


		/**
		 * Gets the value of the typeRef property.
		 *
		 * @return possible object is {@link javax.xml.namespace.QName }
		 *
		 */
		public QName getTypeRef() {
			return this.typeRef;
		}

		/**
		 * Sets the value of the typeRef property.
		 *
		 * @param value allowed object is {@link javax.xml.namespace.QName }
		 * 
		 */
		public void setTypeRef(QName value) {
			this.typeRef = value;
		}
		
	}
	
}
